enum AuthenticationStatusCode {
  USER_NOT_EXIST,
  CONNECTION_FAILED,
  INVALID_PASSWORD,
  INVALID_CREDENTIALS,
  SUCCESS,
  EMAIL_FAILED,
  VERIFICATION_FAILED,
  UPDATE_USER_DETAILS_FAILED,
  INTERNAL_SERVER_ERROR,
}

export default AuthenticationStatusCode;
