version: '3'

services:
  operation-yoga:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: operation-yoga
    environment:
      - PB_VERSION=0.15.1
    ports:
      - '3001:3000'
      - '8081:8080'